id: composer
type: bidirectional
components:
  - id: in
    type: entry
    bean: basicEntry
    next: composer

  - id: composer
    type: composer
    bean: bufferComposer
    configuration:
      size: 3
    next: out

  - id: out
    type: sink
    bean: bidirectionalSink